# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: deploy
          command: |
            npm install -g firebase-tools@3.0.7
      - deploy:
          command: |
            firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
