machine:
    node:
      version: 7.4.0
    post:
      - curl -o- -L https://yarnpkg.com/install.sh | bash
    timezone: Asia/Tokyo

dependencies:
  cache_directories:
    - ~/.cache/yarn
  pre:
    - yarn --version
  override:
    - npm install -g firebase-tools@3.0.7

deployment:
  deploy:
    branch: master
    commands:
      - firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"
